/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author igo
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
        /**
         * Inicia o texto do balão do gênio
         */
        lblTextoBalao.setText("<html>Vou pensar em um valor entre 1 e 2, tente advinhar!<html>");
        /**
         * Pega a dificuldade que esta no combo box e coloca no lblBalaoDificuldade
         */
        String dificuldade = (String) cmbDificuldade.getSelectedItem();
        lblBalaoDificuldade.setText(dificuldade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenio = new javax.swing.JLabel();
        lblTextoBalao = new javax.swing.JLabel();
        lblBalaoDificuldade = new javax.swing.JLabel();
        lblBalaoGenio = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        spnPalpiteUsuario = new javax.swing.JSpinner();
        cmbDificuldade = new javax.swing.JComboBox<>();
        lblTextoDificuldade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genio.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 350, 400));

        lblTextoBalao.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblTextoBalao.setText("jLabel1");
        getContentPane().add(lblTextoBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 350, 210));

        lblBalaoDificuldade.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblBalaoDificuldade.setText("jLabel1");
        getContentPane().add(lblBalaoDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        lblBalaoGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balaodafrase.png"))); // NOI18N
        lblBalaoGenio.setText("jLabel1");
        getContentPane().add(lblBalaoGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 520, 470));

        btnPalpite.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        btnPalpite.setText("PALPITE");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, -1));

        spnPalpiteUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        spnPalpiteUsuario.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000000, 1));
        getContentPane().add(spnPalpiteUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 290, -1));

        cmbDificuldade.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        cmbDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebê", "Fácil", "Médio", "Difícil " }));
        cmbDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDificuldadeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblTextoDificuldade.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblTextoDificuldade.setText("Dificuldade");
        getContentPane().add(lblTextoDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        /**
         * Gera o número que o gênio está pensando
         */
        int numGenio;
        /**
         * Captura o palpite do usuário
         */
        int palpiteUsuario = (int) spnPalpiteUsuario.getValue();
        /**
         * Capura a dificuldade 
         */
        String dificuldade = (String) cmbDificuldade.getSelectedItem();
        /**
         * Dependendo da dificuldade, será gerado números maiores ou menos
         */
        if(dificuldade.equals("Bebê")){
            numGenio = (int) (Math.random() * 2) + 1;
        }else if (dificuldade.equals("Fácil")){
           numGenio = (int) (Math.random() * 5) + 1;
        }else if(dificuldade.equals("Médio")){
           numGenio = (int) (Math.random() * 32) + 1;
        }else{
            numGenio = (int) (Math.random() * 1000000) + 1;
        }
        
        /**
         * Compara o número gerado com o número do usuário
         * se for o mesmo, imprime acertou, do contrario
         * informa o valor gerado.
         */
        if(numGenio == palpiteUsuario){
            lblTextoBalao.setText("Acertou!");
        }else{
            lblTextoBalao.setText("<html>Errou! Eu pensei no número: " + numGenio);
        }
    }//GEN-LAST:event_btnPalpiteActionPerformed

    private void cmbDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDificuldadeActionPerformed
        // TODO add your handling code here:
       
        //dificulade: Bebê, Fácil, Médio, Difícil.
        
        String dificuldade = (String) cmbDificuldade.getSelectedItem();
        /**
         * Captura a dificuldade e adiciona no lblBalaoDificuldade e 
         * muda o texto do gênio 
         */
        if(dificuldade.equals("Bebê")){
            lblBalaoDificuldade.setText("Bebê");
            lblTextoBalao.setText("<html>Vou pensar em um valor entre 1 e 2, tente advinhar!<html>");
        }else if (dificuldade.equals("Fácil")){
            lblBalaoDificuldade.setText(dificuldade);
            lblTextoBalao.setText("<html>Vou pensar em um valor entre 1 e 5, tente advinhar!<html>");
        }else if(dificuldade.equals("Médio")){
            lblBalaoDificuldade.setText(dificuldade);
            lblTextoBalao.setText("<html>Vou pensar em um valor entre 1 e 32, tente advinhar!<html>");
        }else{
            lblBalaoDificuldade.setText(dificuldade);
            lblTextoBalao.setText("<html>Vou pensar em um valor entre 1 e 1.000.000, tente advinhar!<html>");
        }
    }//GEN-LAST:event_cmbDificuldadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JComboBox<String> cmbDificuldade;
    private javax.swing.JLabel lblBalaoDificuldade;
    private javax.swing.JLabel lblBalaoGenio;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblTextoBalao;
    private javax.swing.JLabel lblTextoDificuldade;
    private javax.swing.JSpinner spnPalpiteUsuario;
    // End of variables declaration//GEN-END:variables
}
