/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

import java.time.LocalDate;

/**
 *
 * @author igo
 */
public class CalculadoradeIdade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoradeIdade.class.getName());

    /**
     * Creates new form CalculadoradeIdade
     */
    public CalculadoradeIdade() {
        initComponents();
        
        /**
         * Busca o ano atual e adiciona no spinner
         */
        LocalDate ano = LocalDate.now();
        spnIdadeInserida.setValue(ano.getYear());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        lblAnoDeNascimento = new javax.swing.JLabel();
        spnIdadeInserida = new javax.swing.JSpinner();
        btnCalcularIdade = new javax.swing.JButton();
        lblImagemPerfil = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        lblViajante = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAnoDeNascimento.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblAnoDeNascimento.setText("Ano de Nascimento");
        getContentPane().add(lblAnoDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        spnIdadeInserida.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        getContentPane().add(spnIdadeInserida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 230, -1));

        btnCalcularIdade.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        btnCalcularIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/image/calculadoraicone.png"))); // NOI18N
        btnCalcularIdade.setText("Calcular Idade");
        btnCalcularIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblImagemPerfil.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblImagemPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/image/perfilicon.png"))); // NOI18N
        getContentPane().add(lblImagemPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 250, 260));

        lblResultado.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        lblResultado.setText("...................................................");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 580, -1));

        lblViajante.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblViajante.setText("jLabel1");
        getContentPane().add(lblViajante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIdadeActionPerformed
        // TODO add your handling code here:
        LocalDate ano = LocalDate.now();
        int idade = (int) spnIdadeInserida.getValue();
        /**
         * Faz o calculo da idade 
         */
        int resultado = ano.getYear() - idade;
        
        if(resultado < 0){
            /**
             * Se idade for menor do que 0, imprime essa mensagem na tela
             */
           lblViajante.setText("CALMA, VIAJANTE NO TEMPO!");
        }else{
            /**
             * "Zera" a o lblViajante
             */
           lblViajante.setText("");
           
           if(resultado == 1){
               /**
                * Se idade for igual a 1, remove o s de anos
                */
              lblResultado.setText("Você tem " + resultado + " ano");
              return; 
           }
           /**
            * Mosa mensagem mais a idade
            */
           lblResultado.setText("Você tem " + resultado + " anos");
        }
        
    }//GEN-LAST:event_btnCalcularIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoradeIdade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularIdade;
    private javax.swing.JLabel lblAnoDeNascimento;
    private javax.swing.JLabel lblImagemPerfil;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblViajante;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JSpinner spnIdadeInserida;
    // End of variables declaration//GEN-END:variables
}
