/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import br.com.ifba.atividade09.classe.Pagamento;
import br.com.ifba.atividade09.classe.PagamentoCartao;
import br.com.ifba.atividade09.classe.PagamentoDinheiro;
import br.com.ifba.atividade09.classe.PagamentoPix;

/**
 *
 * @author igo
 */
public class PagamentoUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PagamentoUsuario.class.getName());

    /**
     * Creates new form PagamentoUsuario
     */
    public PagamentoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoInformativo = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblTextoFormaDePagamento = new javax.swing.JLabel();
        cmbFormaDePagamento = new javax.swing.JComboBox<>();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTextoInformativo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblTextoInformativo.setText("Informe o Valor do Pagamento R$");

        txtValor.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        lblTextoFormaDePagamento.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblTextoFormaDePagamento.setText("Forma de pagamento: ");

        cmbFormaDePagamento.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        cmbFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "Pix", "Dinheiro" }));

        btnPagar.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblTextoInformativo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblTextoFormaDePagamento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(cmbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnPagar)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(lblTextoInformativo)
                .addGap(18, 18, 18)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTextoFormaDePagamento)
                .addGap(18, 18, 18)
                .addComponent(cmbFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnPagar)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
       /**
        * Pega o valor e o tipo de pagamento do usuário
        */
      float valor = Float.parseFloat(txtValor.getText());
      String tipoPagamento = (String) cmbFormaDePagamento.getSelectedItem();
      /**
       * Escolhe qual o metodo de pagamento, e com isso, escolhe o calculo adequado
       */
      if(tipoPagamento.equals("Cartão")){
          Pagamento pagaCartao = new PagamentoCartao(valor);
          pagaCartao.ImprimirRecibo();
      }else if(tipoPagamento.equals("Pix")){
          Pagamento pagaPix = new PagamentoPix(valor);
          pagaPix.ImprimirRecibo();
      }else{
          Pagamento pagaDinheiro = new PagamentoDinheiro(valor);
          pagaDinheiro.ImprimirRecibo();
      }

    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PagamentoUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> cmbFormaDePagamento;
    private javax.swing.JLabel lblTextoFormaDePagamento;
    private javax.swing.JLabel lblTextoInformativo;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
