/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author igo
 */
public class ContarSlider extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContarSlider.class.getName());

    /**
     * Creates new form ContarSlider
     */
    public ContarSlider() {
        initComponents();
        /**
         * Iniando os os lbl com o valor definido em cada slider 
         */
        lblTextoInicio.setText(Integer.toString(sldInicio.getValue()));
        lblTextoFim.setText(Integer.toString(sldFim.getValue()));
        lblTextoPasso.setText(Integer.toString(sldPasso.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblTextoFim = new javax.swing.JLabel();
        lblTextoPasso = new javax.swing.JLabel();
        lblTextoInicio = new javax.swing.JLabel();
        sldInicio = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnContar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFim.setText("FIm");
        getContentPane().add(lblFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblPasso.setText("Passo");
        getContentPane().add(lblPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblInicio.setText("Inicio");
        getContentPane().add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblTextoFim.setText("FIm");
        getContentPane().add(lblTextoFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        lblTextoPasso.setText("Passo");
        getContentPane().add(lblTextoPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        lblTextoInicio.setText("Inicio");
        getContentPane().add(lblTextoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        sldInicio.setMaximum(1000);
        sldInicio.setValue(1);
        sldInicio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldInicioStateChanged(evt);
            }
        });
        getContentPane().add(sldInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 680, -1));

        sldFim.setMaximum(1000);
        sldFim.setMinimum(1);
        sldFim.setValue(1);
        sldFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFimStateChanged(evt);
            }
        });
        getContentPane().add(sldFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 680, -1));

        sldPasso.setMaximum(1000);
        sldPasso.setMinimum(1);
        sldPasso.setValue(1);
        sldPasso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPassoStateChanged(evt);
            }
        });
        getContentPane().add(sldPasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 680, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 350, 410));

        btnContar.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        btnContar.setText("Contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 300, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldInicioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldInicioStateChanged
        // TODO add your handling code here:
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        
        /**
         * Caso o início seja maior que o fim ele conserta o final
         */
        if (inicio >= fim) {
            fim = inicio + 1;
            sldFim.setValue(fim); 
        }
       /**
        * Faz o calculo para definir o máximo que passo pode ser
        */
        lblTextoInicio.setText(Integer.toString(inicio));
        int maxPasso = Math.max(fim - inicio, 1);
        sldPasso.setMaximum(maxPasso);
    }//GEN-LAST:event_sldInicioStateChanged

    private void sldFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFimStateChanged
        // TODO add your handling code here:
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        /**
         * Conserta o início, caso o fim seja menor do que o início
         */
        if (fim <= inicio) {
            inicio = fim - 1;
            sldInicio.setValue(inicio); 
        }
        /**
         * Define o valor máximo do passo
         */    
        lblTextoFim.setText(Integer.toString(fim));
        int maxPasso = Math.max(fim - inicio, 1);
        sldPasso.setMaximum(maxPasso);
    }//GEN-LAST:event_sldFimStateChanged

    private void sldPassoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPassoStateChanged
        // TODO add your handling code here:
        /**
         * Pega o valor que esta no slider passo e atualiza o lblTextoPasso
         */
        javax.swing.event.ChangeEvent verificando = new javax.swing.event.ChangeEvent(sldPasso);
        /**
         *  Metodos criados e com  
         */
        sldInicioStateChanged(verificando);
        sldFimStateChanged(verificando);
        
        int passo = sldPasso.getValue();
        lblTextoPasso.setText(Integer.toString(passo));
    }//GEN-LAST:event_sldPassoStateChanged

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        /**
         * Pega os valores do slides 
         */
        int inicio = sldInicio.getValue();
        int fim = sldFim.getValue();
        int passo = sldPasso.getValue();
        /**
         * Limpa o txtArea, apagado os números anteriores
         */
        txtArea.setText("");
        
        /**
         * Imprime os valos definidos nos slides
         */
        for(int i = inicio; i <= fim; i = i + passo){
           txtArea.append(i + "\n");
        }
    }//GEN-LAST:event_btnContarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContarSlider().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JLabel lblTextoFim;
    private javax.swing.JLabel lblTextoInicio;
    private javax.swing.JLabel lblTextoPasso;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldInicio;
    private javax.swing.JSlider sldPasso;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
