/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;
/**
 *
 * @author oxede
 */
import java.time.LocalDate;
public class NewJFrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameCalculadora
     */
    public NewJFrameCalculadora() {
        initComponents();
        //Ao iniciar, irá mostrar o ano atual
        LocalDate dataAtual = LocalDate.now();
        int anoAtual = dataAtual.getYear();
        txtAnoMostrado.setText(Integer.toString(anoAtual));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        txtAnoMostrado = new javax.swing.JTextField();
        btnAumentarAno = new javax.swing.JButton();
        btnDiminuirAno = new javax.swing.JButton();
        btnCalcularIdade = new javax.swing.JButton();
        lblIdade = new javax.swing.JLabel();
        lblIdadeMostrada = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNascimento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNascimento.setText("Ano de Nascimento");

        txtAnoMostrado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtAnoMostrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoMostradoActionPerformed(evt);
            }
        });

        btnAumentarAno.setText("UP");
        btnAumentarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarAnoActionPerformed(evt);
            }
        });

        btnDiminuirAno.setText("Down");
        btnDiminuirAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiminuirAnoActionPerformed(evt);
            }
        });

        btnCalcularIdade.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCalcularIdade.setText("Calcular");
        btnCalcularIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIdadeActionPerformed(evt);
            }
        });

        lblIdade.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblIdade.setText("Idade:");

        lblIdadeMostrada.setFont(new java.awt.Font("Segoe UI", 0, 37)); // NOI18N
        lblIdadeMostrada.setForeground(new java.awt.Color(255, 0, 0));
        lblIdadeMostrada.setText("............");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnCalcularIdade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoMostrado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDiminuirAno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAumentarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdadeMostrada, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAumentarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDiminuirAno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAnoMostrado)
                    .addComponent(lblNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnCalcularIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(lblIdadeMostrada))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnoMostradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoMostradoActionPerformed
        //Trecho comentado por causa que, já está inicializado o ano.
        
        /*LocalDate dataAtual = LocalDate.now();
        int anoAtual = dataAtual.getYear();
        txtAnoMostrado.setText(Integer.toString(anoAtual));*/
    }//GEN-LAST:event_txtAnoMostradoActionPerformed

    private void btnAumentarAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarAnoActionPerformed
       //Pega o ano atual no txtAnoMostrado e incrementa +1
        int anoAtual = Integer.parseInt(txtAnoMostrado.getText());
        anoAtual+= 1;
        txtAnoMostrado.setText(Integer.toString(anoAtual));
    }//GEN-LAST:event_btnAumentarAnoActionPerformed

    private void btnDiminuirAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiminuirAnoActionPerformed
        //Pega o ano atual no txtAnoMostrado e decrementa -1
        int anoAtual = Integer.parseInt(txtAnoMostrado.getText());
        anoAtual+= - 1;
        txtAnoMostrado.setText(Integer.toString(anoAtual));
    }//GEN-LAST:event_btnDiminuirAnoActionPerformed

    private void btnCalcularIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIdadeActionPerformed
        //Pega o ano atual
        LocalDate dataAtual = LocalDate.now();
        int anoAtual = dataAtual.getYear();
        //Pega o ano escolhido pelo usuário
        int idadePega = Integer.parseInt(txtAnoMostrado.getText());
        //Faz o calculo da idade
        int resultado = anoAtual - idadePega;
        //Verificando se a idade é menor do que 0, caso seja, entra na condição
        if(resultado < 0){
            lblIdadeMostrada.setText("Ainda não Nasceu!");
        }else{
            lblIdadeMostrada.setText(Integer.toString(resultado));
    }
    }//GEN-LAST:event_btnCalcularIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentarAno;
    private javax.swing.JButton btnCalcularIdade;
    private javax.swing.JButton btnDiminuirAno;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdadeMostrada;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JTextField txtAnoMostrado;
    // End of variables declaration//GEN-END:variables
}
